import {
  LayoutDashboard,
  ShoppingCart,
  Package,
  Database,
  Users,
  BarChart3,
  Settings,
  ArrowDownLeft,
  ArrowRightLeft,
  Briefcase,
  FolderTree,
  Building2,
  FileText,
  Wallet,
  Coins,
  ScrollText,
  Percent,
  Banknote,
  History as HistoryIcon,
  Box,
  Layers,
  ShieldCheck,
  Warehouse,
  Shield,
  Trash2,
  ArrowUpRight
} from 'lucide-react';

export const pageGroups = [
  {
    id: 'pos',
    label: 'نقاط البيع',
    icon: ShoppingCart,
    color: 'blue',
    masterKey: 'pos',
    pages: [
      { key: 'pos', label: 'نقطة البيع (POS)', desc: 'إجراء عمليات البيع للكاشير', icon: ShoppingCart },
      { key: 'adminPos', label: 'POS للمدير — إدارة', desc: 'شاشة البيع الإدارية مع كل الصلاحيات', icon: ShieldCheck },
      { key: 'branchManagement', label: 'إدارة الفرع', desc: 'متابعة إحصائيات وأداء الفرع', icon: LayoutDashboard },
      { key: 'cashierManagement', label: 'إدارة الكاشير', desc: 'إدارة الموظفين وصلاحياتهم', icon: ShieldCheck },
      { key: 'pos_make_return', label: 'عمل مرتجع للفاتورة', desc: 'السماح للكاشير بعمل مرتجع للفواتير المكتملة', icon: ArrowRightLeft },
      { key: 'pos_delete_invoice', label: 'إلغاء/حذف الفاتورة المعلقة', desc: 'السماح للكاشير بإلغاء أو حذف الفواتير المعلقة', icon: Trash2 },
    ]
  },
  {
    id: 'inventory',
    label: 'المخازن والمستودعات',
    icon: Warehouse,
    color: 'orange',
    masterKey: 'inventory',
    pages: [
      { key: 'inventory', label: 'لوحة المخزون', desc: 'ملخص وإحصائيات المخزن', icon: LayoutDashboard },
      { key: 'inventory_products', label: 'الأصناف', desc: 'إدارة قائمة الأصناف', icon: Package },
      { key: 'inventory_units', label: 'وحدات القياس', desc: 'إدارة وحدات الوزن والعدد', icon: Box },
      { key: 'inventory_itemmap', label: 'خريطة الأصناف', desc: 'تصنيف وتخطيط الأصناف', icon: Layers },
      { key: 'inventory_warehouses', label: 'المستودعات', desc: 'إدارة المستودعات للفروع', icon: Building2 },
      { key: 'inventory_receipt', label: 'توريد بضاعة', desc: 'استلام البضائع الواردة', icon: ArrowDownLeft },
      { key: 'inventory_salesreturns', label: 'مردودات مبيعات', desc: 'إرجاع البضائع المباعة', icon: ArrowRightLeft },
      { key: 'inventory_transfer_receipt', label: 'استلام تحويل بضاعة', desc: 'تأكيد استلام البضائع المحولة', icon: ArrowDownLeft },
      { key: 'inventory_purchasereturns', label: 'مردودات مشتريات', desc: 'إرجاع المشتريات للموردين', icon: ArrowDownLeft },
      { key: 'inventory_issue', label: 'صرف بضاعة', desc: 'صرف البضائع من المخزن', icon: Database },
      { key: 'inventory_branchtransfer', label: 'طلب تحويل بضاعة', desc: 'طلبات نقل البضائع بين الفروع', icon: ArrowRightLeft },
      { key: 'inventory_transfers', label: 'تحويل بضاعة', desc: 'تنفيذ التحويلات بين المستودعات', icon: ArrowRightLeft },
      { key: 'inventory_opening', label: 'الرصيد الافتتاحي', desc: 'ضبط الأرصدة الأولية', icon: FileText },
      { key: 'inventory_stocktaking', label: 'جرد المخزون', desc: 'حصر وإعادة تقييم المخزون', icon: HistoryIcon },
      { key: 'inventory_approval', label: 'تصديقات المخازن', desc: 'اعتماد حركات المخزون', icon: ShieldCheck },
      { key: 'inventory_payable', label: 'الحسابات الدائنة', desc: 'حسابات الموردين والديون', icon: Wallet },
      { key: 'inventory_reports', label: 'تقارير المخزون', desc: 'تقارير الحركة والمخزون', icon: BarChart3 },
    ]
  },
  {
    id: 'accounting',
    label: 'الحسابات والمالية',
    icon: Briefcase,
    color: 'purple',
    masterKey: 'accounting',
    pages: [
      { key: 'accounting', label: 'لوحة الحسابات', desc: 'ملخص ومتابعة الحسابات', icon: Briefcase },
      { key: 'accounting_chart', label: 'دليل الحسابات', desc: 'شجرة الحسابات المالية', icon: FolderTree },
      { key: 'accounting_costcenters', label: 'مراكز التكلفة', desc: 'إدارة مراكز التكلفة', icon: Building2 },
      { key: 'accounting_currencies', label: 'العملات', desc: 'إدارة العملات وأسعار الصرف', icon: Coins },
      { key: 'accounting_checkstages', label: 'مراحل الشيكات', desc: 'متابعة دورة حياة الشيكات', icon: ScrollText },
      { key: 'accounting_taxes', label: 'الضرائب', desc: 'إعداد نسب الضرائب والرسوم', icon: Percent },
      { key: 'accounting_journal', label: 'قيود اليومية', desc: 'إدخال القيود المحاسبية', icon: FileText },
      { key: 'accounting_cash', label: 'النقدية والصيرفة', desc: 'إدارة حركات النقد والصرافة', icon: Wallet },
    ]
  },
  {
    id: 'sales',
    label: 'إدارة المبيعات',
    icon: Coins,
    color: 'blue',
    masterKey: 'sales',
    pages: [
      { key: 'sales', label: 'لوحة المبيعات', desc: 'ملخص وإحصائيات أداء المبيعات', icon: LayoutDashboard },
      { key: 'sales_basic', label: 'بيانات أساسية مبيعات', desc: 'العملاء، المندوبين، الخدمات، قوائم الأسعار، فروع المبيعات، مستهدفات وحوافز البيع', icon: Users },
      { key: 'sales_config', label: 'ضبط إعدادات المبيعات', desc: 'ضبط لوائح وسياسات وضوابط العملاء والبيع', icon: Settings },
      { key: 'sales_docs', label: 'مستندات المبيعات', desc: 'أمر البيع، المرتجعات، عروض الأسعار، الدوري', icon: FileText },
      { key: 'sales_approvals', label: 'تصديقات المبيعات', desc: 'اعتماد المبيعات والمرتجع وتسليم البضاعة', icon: ShieldCheck },
      { key: 'sales_reports', label: 'تقارير المبيعات المتقدمة', desc: 'تقارير الأرباح والمقارنات والتقييمات', icon: BarChart3 },
    ]
  },
  {
    id: 'system',
    label: 'النظام والتقارير',
    icon: Settings,
    color: 'slate',
    masterKey: 'reports',
    pages: [
      { key: 'dashboard', label: 'لوحة التحكم الرئيسية', desc: 'إحصائيات وملخص النظام', icon: LayoutDashboard },
      { key: 'customers', label: 'إدارة العملاء', desc: 'بيانات العملاء وحساباتهم', icon: Users },
      { key: 'reports', label: 'تقارير المبيعات', desc: 'سجلات المبيعات والأداء', icon: BarChart3 },
      { key: 'reports_cash', label: 'تقارير الكاش والشفتات', desc: 'تقارير الصناديق ونهاية اليوم', icon: Banknote },
      { key: 'reports_history', label: 'سجل المبيعات (History)', desc: 'تاريخ كامل لعمليات البيع', icon: HistoryIcon },
      { key: 'reports_center', label: 'مركز التقارير الموحد', desc: 'جميع التقارير في مكان واحد', icon: BarChart3 },
      { key: 'settings', label: 'إعدادات النظام', desc: 'إعدادات الشركة والطباعة', icon: Settings },
      { key: 'systemReset', label: 'إعادة تهيئة النظام', desc: 'حذف البيانات وتصفير النظام', icon: Shield },
    ]
  },
];
